# Generated by Django 4.2.2 on 2023-06-21 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=10)),
                ('country_code_2', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectorName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='YearData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchartapi.country')),
            ],
        ),
        migrations.CreateModel(
            name='Subsector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subSectorName', models.CharField(max_length=100)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchartapi.sector')),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicatorName', models.CharField(max_length=100)),
                ('countries', models.ManyToManyField(to='searchartapi.country')),
                ('subsector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchartapi.subsector')),
            ],
        ),
    ]
