# Generated by Django 4.2.2 on 2023-06-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchartapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='indicator',
            options={'verbose_name': 'Indicator', 'verbose_name_plural': 'Indicators'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name': 'Sector', 'verbose_name_plural': 'Sectors'},
        ),
        migrations.AlterModelOptions(
            name='subsector',
            options={'verbose_name': 'Subsector', 'verbose_name_plural': 'Subsectors'},
        ),
        migrations.AlterField(
            model_name='yeardata',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
