# Generated by Django 4.2.2 on 2023-07-27 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchartapi', '0002_alter_yeardata_country_code_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yeardata',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='yeardata',
            name='country_code_2',
        ),
    ]
