# Generated by Django 4.2.2 on 2023-07-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchartapi', '0003_remove_yeardata_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yeardata',
            name='country_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='yeardata',
            name='country_code_2',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
