# Generated by Django 4.2.2 on 2023-06-23 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchartapi', '0003_alter_yeardata_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='yeardata',
            name='indicator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='searchartapi.indicator'),
            preserve_default=False,
        ),
    ]
