# Generated by Django 4.2.2 on 2023-08-01 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchartapi', '0004_yeardata_country_code_yeardata_country_code_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='searchartapi.country')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchartapi.indicator')),
            ],
        ),
    ]
