# Generated by Django 4.2.2 on 2023-08-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchartapi', '0005_maindata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindata',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
