# Generated by Django 4.2.2 on 2023-07-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchartapi', '0005_alter_subsector_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='indicatorName',
            field=models.CharField(max_length=160),
        ),
    ]
